# Site settings
title: Bangladesh IATI &ndash; AIMS import
description: Developing a sustainable process for importing IATI data to Bangladesh's AIMS
baseurl: ""
url: "http://bd-iati.github.io" # the base hostname & protocol for your site
github_username:  bd-iati
email: bd-iati@brough.io

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
pagine_path: "blog/page:num"
paginate: 10

collections:
  documentation:
    output: true
  background:
    output: true
  dpdata:
    output: true
  development:
    output: true
  finalreport:
    output: true

gems: [jekyll-paginate]

exclude: [bower_components]

keep_files: [bower_components]

authors:
  mark:
    name: Mark Brough
    display_name: Mark
    email: mark@brough.io
    web: http://brough.io
    twitter: mark_brough
    github: markbrough
